apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: domoya-ga-tls
spec:
  secretName: domoya-ga
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuser
  commonName: domoya.ga
  dnsNames:
    - domoya.ga
    - www.domoya.ga
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - domoya.ga
          - www.domoya.ga
